# .NET Core Function App to Windows on Azure
# Build a .NET Core function app and deploy it to Azure as a Windows function App.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/en-us/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

variables:
  # Function app name
  functionAppName: 'cchatinvoiceprocessor'

  # Agent VM image name
  vmImageName: 'vs2017-win2016'

  # Working Directory
  workingDirectory: '$(System.DefaultWorkingDirectory)/CCHat.InvoiceProcessor'

stages:
- stage: Build
  displayName: Build stage

  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: $(vmImageName)

    steps:
    - task: DotNetCoreCLI@2
      displayName: Build
      inputs:
        command: 'build'
        projects: |
          $(workingDirectory)/*.csproj
        arguments: --output $(System.DefaultWorkingDirectory)/publish_output --configuration Release

    - task: ArchiveFiles@2
      displayName: 'Archive files'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/publish_output'
        includeRootFolder: false
        archiveType: zip
        archiveFile: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
        replaceExistingArchive: true

    - publish: $(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip
      displayName: BuildArtifact
      artifact: drop

    - publish: $(workingDirectory)/Deploy
      displayName: ARM Templates
      artifact: deploy  


- stage: DEV  
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: DEV
    displayName: DEV
    environment: DEV
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Validate ARM'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(azureSubscription)'
              subscriptionId: '$(subscriptionId)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'cchatdemorg'
              location: 'Australia Southeast'
              templateLocation: 'Linked artifact'              
              csmFile: '$(Pipeline.Workspace)/deploy/template.json'
              csmParametersFile: '$(Pipeline.Workspace)/deploy/template.parameters.json'
              overrideParameters: '-appName $(functionAppName)-dev'
              deploymentMode: 'Validation'

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploy Azure Function Infrastructure'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(azureSubscription)'
              subscriptionId: '$(subscriptionId)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'cchatdemorg'
              location: 'Australia Southeast'
              templateLocation: 'Linked artifact'              
              csmFile: '$(Pipeline.Workspace)/deploy/template.json'
              csmParametersFile: '$(Pipeline.Workspace)/deploy/template.parameters.json'
              overrideParameters: '-appName $(functionAppName)-dev'              
              deploymentMode: 'Incremental'

          - task: AzureFunctionApp@1
            displayName: 'Deploy Azure Function App'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionApp
              appName: '$(functionAppName)'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'

- stage: TEST  
  dependsOn: Build
  condition: succeeded()

  jobs:
  - deployment: TEST
    displayName: TEST
    environment: TEST
    pool:
      vmImage: $(vmImageName)

    strategy:
      runOnce:
        deploy:

          steps:
          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Validate ARM'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(azureSubscription)'
              subscriptionId: '$(subscriptionId)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'cchatdemotestrg'
              location: 'Australia Southeast'
              templateLocation: 'Linked artifact'              
              csmFile: '$(Pipeline.Workspace)/deploy/template.json'
              csmParametersFile: '$(Pipeline.Workspace)/deploy/template.parameters.json'
              overrideParameters: '-appName $(functionAppName)-test'
              deploymentMode: 'Validation'

          - task: AzureResourceManagerTemplateDeployment@3
            displayName: 'Deploy Azure Function Infrastructure'
            inputs:
              deploymentScope: 'Resource Group'
              azureResourceManagerConnection: '$(azureSubscription)'
              subscriptionId: '$(subscriptionId)'
              action: 'Create Or Update Resource Group'
              resourceGroupName: 'cchatdemotestrg'
              location: 'Australia Southeast'
              templateLocation: 'Linked artifact'              
              csmFile: '$(Pipeline.Workspace)/deploy/template.json'
              csmParametersFile: '$(Pipeline.Workspace)/deploy/template.parameters.json'
              overrideParameters: '-appName $(functionAppName)-test'              
              deploymentMode: 'Incremental'

          - task: AzureFunctionApp@1
            displayName: 'Deploy Azure Function App'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: functionApp
              appName: '$(functionAppName)'
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'